### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by jacqueswww** [tintinweb/vscode-vyper#1]
Very cool plugin.

**Comment by widyhafiz03** [comment]
ext install tintinweb.vscode-vyper

**Comment by tintinweb** [comment]
haha, what a pleasant surprise, I was expecting something to fix but that's way better - yay! 🎉 

you guys are doing a great job with vyper! let me know if there's anything you are missing in the extension. happy to help on the road to mass adoption :)
