### ISSUE TITLE
Publish extension on Open VSX registry to make it available in GitPod

### ISSUE THREAD

**Issue by Unstoppable-DeFi** [tintinweb/vscode-vyper#28]
Can we please publish the extension to the Open VSX registry?

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by wschwab** [comment]
This would also make it available to anyone using Arch and a number of its derivatives, afaict. It doesn't look too bad imho, I can try to do it myself if you'd like, but would mean that I'd need to push every time there's an update. The better path would likely be using the GitHub Action at the end of the page that @Unstoppable-DeFi linked, which in turn links to [here](https://github.com/HaaLeo/publish-vscode-extension#readme).

**Comment by tintinweb** [comment]
🥳 https://open-vsx.org/extension/tintinweb/vscode-vyper
